#!/bin/bash

#
# Set the following to match the Live version you are using:
#
#
EDITION="Ableton Live 12 Suite"
VERSION="12.0.20"

# Create shared preferences folder and allow rw permissions

mkdir -p "/Library/Preferences/Ableton/Live ${VERSION}/"
chmod a+rw "/Library/Preferences/Ableton/Live ${VERSION}/"
  
# Add Options.txt entries

echo "-LicenseServer" > "/Library/Preferences/Ableton/Live ${VERSION}/Options.txt" 
echo "-_DisableAutoUpdates" >> "/Library/Preferences/Ableton/Live ${VERSION}/Options.txt"

# Create shared Packs folder

mkdir -p "/Users/Shared/Ableton/Factory Packs/"

# Run Ableton Live and capture its exit code
open "/Applications/${EDITION}.app/Contents/MacOS/Live"


# Capture the exit code
LIVE_EXIT_CODE=$?

# Check the exit code
if [ ${LIVE_EXIT_CODE} -ne 0 ]; then
    echo "Ableton ${EDITION} Sassafras authorization failed with exit code ${LIVE_EXIT_CODE}"
    exit ${LIVE_EXIT_CODE}
else
    echo "Ableton ${EDITION} was successfully configured for and authorized with Sassafras."
    exit 0
fi
